[package]
name = "day01"
version = "0.1.0"
authors = ["arne"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
petgraph = "0.4.13"
